"""milestone 4.9 indexes

Revision ID: 0960d4911543
Revises: 4cdb0d9abefb
Create Date: 2026-06-21 18:40:36.775257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0960d4911543'
down_revision: Union[str, None] = '4cdb0d9abefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_admin_audit_log_action', 'admin_audit_log', ['action'], unique=False)
    op.create_index('idx_admin_audit_log_admin_id', 'admin_audit_log', ['admin_user_id'], unique=False)
    op.create_index('idx_admin_audit_log_created_at', 'admin_audit_log', ['created_at'], unique=False)
    op.create_index('idx_ai_requests_model_id', 'ai_requests', ['model_id'], unique=False)
    op.create_index('idx_ai_requests_user_id', 'ai_requests', ['user_id'], unique=False)
    op.create_index('idx_prompt_versions_key_active', 'prompt_versions', ['prompt_key', 'is_active'], unique=False)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_prompt_versions_key_active', table_name='prompt_versions')
    op.drop_index('idx_ai_requests_user_id', table_name='ai_requests')
    op.drop_index('idx_ai_requests_model_id', table_name='ai_requests')
    op.drop_index('idx_admin_audit_log_created_at', table_name='admin_audit_log')
    op.drop_index('idx_admin_audit_log_admin_id', table_name='admin_audit_log')
    op.drop_index('idx_admin_audit_log_action', table_name='admin_audit_log')
    # ### end Alembic commands ###
