"""Add AnalysisSession

Revision ID: 0658d77a9003
Revises: 2026_06_21_2130_add_google_id
Create Date: 2026-06-26 15:42:47.131608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0658d77a9003'
down_revision: Union[str, None] = '2026_06_21_2130_add_google_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('analyzer', sa.String(length=50), nullable=False),
    sa.Column('template_origin', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_opened', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_sessions_created', 'analysis_sessions', ['started_at'], unique=False)
    op.create_index('idx_analysis_sessions_user_id', 'analysis_sessions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_analysis_sessions_user_id', table_name='analysis_sessions')
    op.drop_index('idx_analysis_sessions_created', table_name='analysis_sessions')
    op.drop_table('analysis_sessions')
    # ### end Alembic commands ###
